#!/bin/bash

yay -S base-devel strip fakeroot mc fish python2 grc exa neovim python-pynvim python2-pynvim nerd-fonts-hack kitty fzf 

curl -sLf https://spacevim.org/install.sh | bash -s -- --install neovim

fish --command '.config/yadm/bootstrap.fish'

